SygnusportalWEB/Controllers/EmpresasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SygnusportalBD;

namespace SygnusportalWEB.Controllers
{
    public class EmpresasController : Controller
    {
        private sygnusportalEntities db = new sygnusportalEntities();

        // GET: Empresas
        public ActionResult Index()
        {
            var empresa = db.Empresa.Include(e => e.Ciudad);
            return View(empresa.ToList());
        }

        // GET: Empresas/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empresa empresa = db.Empresa.Find(id);
            if (empresa == null)
            {
                return HttpNotFound();
            }
            return View(empresa);
        }

        // GET: Empresas/Create
        public ActionResult Create()
        {
            PaisBD BDPais = new PaisBD();
            var TPais = BDPais.Pais_List(null).ToList();
            string pai_codigo = TPais.First().pai_codigo;

            DepartamentoBD BDDepartamento = new DepartamentoBD();
            var TDepartamento = BDDepartamento.Departamento_List_Pais(pai_codigo).ToList();
            string dep_codigo = "";
            if (TDepartamento.Count != 0)
            {
                dep_codigo = TDepartamento.First().dep_codigo;
            }           
            ViewBag.pai_codigo = new SelectList(TPais, "pai_codigo", "pai_nombre");
            ViewBag.dep_codigo = new SelectList(TDepartamento, "dep_codigo", "dep_nombre");
            ViewBag.ciu_codigo = new SelectList(db.Ciudad_List_Departamento(dep_codigo), "ciu_codigo", "ciu_nombre");




            ViewBag.ciu_codigo = new SelectList(db.Ciudad, "ciu_codigo", "ciu_nombre");
            return View();
        }

        // POST: Empresas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "emp_nit,emp_dv,emp_nombre,emp_direccion,ciu_codigo,emp_telefono,emp_logo,emp_url")] Empresa empresa, HttpPostedFileBase file)
        {

            if (file != null)
            {
                var nombreArchivo = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Uploads"), nombreArchivo);
                file.SaveAs(path);
                empresa.emp_logo = "/Uploads/" + nombreArchivo;
            }


            if (ModelState.IsValid)
            {
                try
                {
                    db.Empresa.Add(empresa);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception Ex)
                {
                    ViewBag.Err = "Error al tratar de guardar el Registro " + Ex.Message;
                }
            }
            PaisBD BDPais = new PaisBD();
            var TPais = BDPais.Pais_List(null).ToList();
            string pai_codigo = TPais.First().pai_codigo;

            DepartamentoBD BDDepartamento = new DepartamentoBD();
            var TDepartamento = BDDepartamento.Departamento_List_Pais(pai_codigo).ToList();
            string dep_codigo = "";
            if (TDepartamento.Count != 0)
            {
                dep_codigo = TDepartamento.First().dep_codigo;
            }
            ViewBag.pai_codigo = new SelectList(TPais, "pai_codigo", "pai_nombre");
            ViewBag.dep_codigo = new SelectList(TDepartamento, "dep_codigo", "dep_nombre");
            ViewBag.ciu_codigo = new SelectList(db.Ciudad_List_Departamento(dep_codigo), "ciu_codigo", "ciu_nombre");

            ViewBag.ciu_codigo = new SelectList(db.Ciudad, "ciu_codigo", "ciu_nombre", empresa.ciu_codigo);
            return View(empresa);
        }

        // GET: Empresas/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empresa empresa = db.Empresa.Find(id);
            if (empresa == null)
            {
                return HttpNotFound();
            }
            ViewBag.ciu_codigo = new SelectList(db.Ciudad, "ciu_codigo", "ciu_nombre", empresa.ciu_codigo);
            return View(empresa);
        }

        // POST: Empresas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "emp_nit,emp_dv,emp_nombre,emp_direccion,ciu_codigo,emp_telefono,emp_logo,emp_url")] Empresa empresa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(empresa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ciu_codigo = new SelectList(db.Ciudad, "ciu_codigo", "ciu_nombre", empresa.ciu_codigo);
            return View(empresa);
        }

        // GET: Empresas/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empresa empresa = db.Empresa.Find(id);
            if (empresa == null)
            {
                return HttpNotFound();
            }
            return View(empresa);
        }

        // POST: Empresas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Empresa empresa = db.Empresa.Find(id);
            db.Empresa.Remove(empresa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //Metodos Json para llenar combos Departamento y Ciudad
        /// <summary>
        /// Metodo que permite cargar el filtro de departamentos por pais
        /// </summary>
        /// <param name="pai_codigo"></param>
        /// <returns></returns>
        public JsonResult GetDepartamento(string id)
        {
            DepartamentoBD BD = new DepartamentoBD();
            var TDepartamento = BD.Departamento_List_Pais(id).ToList();
            return Json(TDepartamento);


            //return Json(new SelectList(TDepartamento, "Value", "Text", JsonRequestBehavior.AllowGet));
        }

        /// <summary>
        /// Metodo que permite filtrar las ciudades por Departamento
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public JsonResult GetCiudad(string id)
        {
            CiudadBD BD = new CiudadBD();
            var TCiudad = BD.Ciudad_List_Departamento(id).ToList();
            return Json(TCiudad);

        }

    }
}

SygnusportalWEB/Views/Empresas/Create.cshtml
@model SygnusportalBD.Empresa

@{
    ViewBag.Title = "Empresa Create";
}

<p>
    <h2>Empresa Create</h2>
</p>
<ul class="nav nav-tabs">
    <li><a href="@Url.Action("Index")"><i class="far fa-list-alt"></i> Empresa</a></li>
    <li class="active"><a href="@Url.Action("Create")"><i class="far fa-file"></i> Nuevo</a></li>
</ul>
@*@using (Html.BeginForm())*@
@using (Html.BeginForm("Create", "Empresas", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()
    <div class="panel-group">
        <div class="panel panel-success">
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="panel-group">
                            <div class="panel panel-success">
                                <div class="panel-heading">
                                    <h4><i class="fas fa-database"></i> Información Básica</h4>
                                </div>
                                <div class="panel-body">
                                    @if (ViewBag.Err != null)
                                    {
                                        <div class="alert alert-danger">@ViewBag.Err</div>
                                    }

                                <div class="form-horizontal">
                                    @Html.ValidationSummary("", new { @class = "text-danger" })
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.emp_nit, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.emp_nit, new { htmlAttributes = new { @class = "form-control", placeholder = Html.DisplayNameFor(x => x.emp_nit) + " *" } })
                                            @Html.ValidationMessageFor(model => model.emp_nit, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.emp_dv, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.emp_dv, new { htmlAttributes = new { @class = "form-control", placeholder = Html.DisplayNameFor(x => x.emp_dv) + " *" } })
                                            @Html.ValidationMessageFor(model => model.emp_dv, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.emp_nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.emp_nombre, new { htmlAttributes = new { @class = "form-control", placeholder = Html.DisplayNameFor(x => x.emp_nombre) + " *" } })
                                            @Html.ValidationMessageFor(model => model.emp_nombre, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.emp_direccion, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.emp_direccion, new { htmlAttributes = new { @class = "form-control", placeholder = Html.DisplayNameFor(x => x.emp_direccion) + " *" } })
                                            @Html.ValidationMessageFor(model => model.emp_direccion, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.Label("Pais", htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.DropDownList("pai_codigo", null, htmlAttributes: new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.Ciudad.Departamento.pai_codigo, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.Label("Departamento", htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.DropDownList("dep_codigo", null, htmlAttributes: new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.Ciudad.dep_codigo, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.ciu_codigo, "ciu_codigo", htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.DropDownList("ciu_codigo", null, htmlAttributes: new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.ciu_codigo, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.emp_telefono, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.emp_telefono, new { htmlAttributes = new { @class = "form-control", placeholder = Html.DisplayNameFor(x => x.emp_telefono) + " *" } })
                                            @Html.ValidationMessageFor(model => model.emp_telefono, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.emp_url, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.emp_url, new { htmlAttributes = new { @class = "form-control", placeholder = Html.DisplayNameFor(x => x.emp_url) + " *" } })
                                            @Html.ValidationMessageFor(model => model.emp_url, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                </div>

                                </div>
                                <div class="panel-footer">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="panel-group">
                            <div class="panel panel-success">
                                <div class="panel-heading">
                                    <h4><i class="far fa-image"></i> Imágen o Logotipo</h4>
                                </div>
                                <div class="panel-body">
                                    <p>Debe seleccionar una imagen o logotipo para la empresa.</p>
                                    <div class="form-horizontal">
                                        <img src="@Html.DisplayFor(modelItem => Model.emp_logo)" class="img_edit" />
                                        <br />
                                        <div class="form-group">
                                            @Html.Label("Imagen", htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                <input type="file" name="file" class="filestyle" />
                                            </div>
                                            @if (ViewBag.MensajeError != null)
                                            {
                                                <div class="alert alert-danger">@ViewBag.MensajeError</div>
                                            }
                                        </div>

                                        <div class="form-group">
                                            @Html.LabelFor(model => model.emp_logo, htmlAttributes: new { @class = "control-label col-md-2" })
                                            <div class="col-md-10">
                                                @Html.EditorFor(model => model.emp_logo, new { htmlAttributes = new { @class = "form-control", placeholder = Html.DisplayNameFor(x => x.emp_logo) + " *" } })
                                                @Html.ValidationMessageFor(model => model.emp_logo, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="panel-footer">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="panel-footer">
                <button type="submit" id="btnSubmit" class="btn btn-success btn-sm">
                    <span class="glyphicon glyphicon-ok"></span> Guardar
                </button>
                <a class='btn btn-danger btn-sm' href="@Url.Action("Index")">
                    <span class="glyphicon glyphicon-remove"></span> Cancelar
                </a>
            </div>

        </div>
    </div>

    <div id="divLoader" class="modal fade in Loading" role="dialog" style="display:none;">
        <div class="centrado text-center">
            <h2>Procesando..</h2>
            <p></p>
            <img src="~/Content/Imagenes/Loading.gif" alt="Loader" />
        </div>
    </div>

}


@section Scripts {
    <script type="text/javascript">
        $("#emp_nit").focus();

        $(document).delegate(':file', 'change', function () {
            document.getElementById("emp_logo").value = this.value;
        });



        $("#btnSubmit").click(function () {
            $("#divLoader").show();
        });


        $(document).ready(function () {
        $("#pai_codigo").change(function () {
            $("#dep_codigo").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetDepartamento")',
                dataType: 'json',
                data: { id: $("#pai_codigo").val() },
                success: function (states) {
                    $.each(states, function (i, state) {
                        $("#dep_codigo").append('<option value="' + state.dep_codigo + '">' +
                            state.dep_nombre + '</option>');

                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve country states.' + ex);
                }
            });
            return false;
        })
    });


        $(document).ready(function () {
        $("#dep_codigo").change(function () {
            $("#ciu_codigo").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetCiudad")',
                dataType: 'json',
                data: { id: $("#dep_codigo").val() },
                success: function (states) {
                    $.each(states, function (i, state) {
                        $("#ciu_codigo").append('<option value="' + state.ciu_codigo + '">' +
                            state.ciu_nombre + '</option>');

                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve country states.' + ex);
                }
            });
            return false;
        })
    });


    </script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/datatables")

}

SygnusportalWEB/Views/Empresas/Delete.cshtml
@model SygnusportalBD.Empresa

@{
    ViewBag.Title = "Delete";
}

<p>
        <h2>Empresa Delete</h2>
</p>
<ul class="nav nav-tabs">
    <li><a href="@Url.Action("Index")"><i class="far fa-list-alt"></i> Empresa</a></li>
    <li class="active"><a href="@Url.Action("Details",new { id = Model.emp_nit })"><i class="far fa-file"></i> Delete</a></li>
</ul>

       <div class="panel-group">
        <div class="panel panel-success">
            <div class="panel-body">
                <div id="divLoader" class="modal fade in Loading" role="dialog" style="display:none;">
                    <center class="centrado">
                        <h2>Procesando..</h2>
                        <p></p>
                        <img src="~/Content/Imagenes/Loading.gif" alt="Loader" />
                    </center>
                </div>
<div>
    <h3 class="text-center">¿Estás segura de que quieres eliminar el Registro?</h3>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.emp_dv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emp_dv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emp_nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emp_nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emp_direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emp_direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emp_telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emp_telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emp_logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emp_logo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emp_url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emp_url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ciudad.ciu_nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ciudad.ciu_nombre)
        </dd>

    </dl>
</div>
            </div>
            <div class="panel-footer">
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

                <button type="submit" id="btnSubmit" class="btn btn-success btn-sm">
                    <span class="glyphicon glyphicon-ok"></span> Elimiar
                </button>
                <a class='btn btn-danger btn-sm' href="@Url.Action("Index")">
                    <span class="glyphicon glyphicon-remove"></span> Cancelar
                </a>
    }
            </div>
        </div>
    </div>



@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/datatables")
    <script type="text/javascript">
        $("#btnSubmit").click(function () {
            $("#divLoader").show();
        });
    </script>

}

SygnusportalWEB/Views/Empresas/Details.cshtml
@model SygnusportalBD.Empresa

@{
    ViewBag.Title = "Details";
}
<p>
        <h2>Empresa Details</h2>
</p>
<ul class="nav nav-tabs">
    <li><a href="@Url.Action("Index")"><i class="far fa-list-alt"></i> Empresa</a></li>
    <li class="active"><a href="@Url.Action("Details",new { id = Model.emp_nit })"><i class="far fa-file"></i> Detalles</a></li>
</ul>
<div class="panel-group">
        <div class="panel panel-success">
            <div class="panel-body">
<p></p>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.emp_dv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emp_dv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emp_nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emp_nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emp_direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emp_direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emp_telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emp_telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emp_logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emp_logo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emp_url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emp_url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ciudad.ciu_nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ciudad.ciu_nombre)
        </dd>

    </dl>
</div>
                </div>
            <div class="panel-footer">
                <a class='btn btn-success btn-sm' href="@Url.Action("Edit",new { id = Model.emp_nit })">
                    <span class="glyphicon glyphicon-edit"></span> Editar
                </a>

                <a class='btn btn-danger btn-sm' href="@Url.Action("Index")">
                    <span class="glyphicon glyphicon-remove"></span> Cancelar
                </a>

            </div>
        </div>
    </div>

<p>
</p>

SygnusportalWEB/Views/Empresas/Edit.cshtml
@model SygnusportalBD.Empresa

@{
    ViewBag.Title = "Edit";
}

<h2>Empresa Edit</h2>
<ul class="nav nav-tabs">
    <li><a href="@Url.Action("Index")"><i class="far fa-list-alt"></i> Empresa</a></li>
    <li class="active"><a href="@Url.Action("Edit",new { id = Model.emp_nit })"><i class="far fa-file"></i> Editar</a></li>
</ul>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel-group">
        <div class="panel panel-success">
            <div class="panel-body">
                <div id="divLoader" class="modal fade in Loading" role="dialog" style="display:none;">
                    <div class="centrado text-center">
                        <h2>Procesando..</h2>
                        <p></p>
                        <img src="~/Content/Imagenes/Loading.gif" alt="Loader" />
                    </div>
                </div>
                @if (ViewBag.Err != null)
                {
                    <div class="alert alert-danger">@ViewBag.Err</div>
                }
    <div class="form-horizontal">
        @Html.ValidationSummary("", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.emp_nit)

        <div class="form-group">
            @Html.LabelFor(model => model.emp_dv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emp_dv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emp_dv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.emp_nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emp_nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emp_nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.emp_direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emp_direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emp_direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ciu_codigo, "ciu_codigo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ciu_codigo", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ciu_codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.emp_telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emp_telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emp_telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.emp_logo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emp_logo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emp_logo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.emp_url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emp_url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emp_url, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>
                </div>
            <div class="panel-footer">
                <button type="submit" id="btnSubmit" class="btn btn-success btn-sm">
                    <span class="glyphicon glyphicon-ok"></span> Guardar
                </button>
                <a class='btn btn-danger btn-sm' href="@Url.Action("Index")">
                    <span class="glyphicon glyphicon-remove"></span> Cancelar
                </a>

            </div>
        </div>
    </div>

}


@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/datatables")
    <script type="text/javascript">
        $("#emp_nit").focus();

        $("#btnSubmit").click(function () {
            $("#divLoader").show();
        });
    </script>

}